runGraph: UndirectedUnweightedGraph.h UndirectedUnweightedGraph.cpp main.cpp
	g++ -std=c++11 -o runGraph main.cpp UndirectedUnweightedGraph.cpp

#runGraph: LinkedList.h LinkedList.cpp DirectedWeightedGraph.h DirectedWeightedGraph.cpp main.cpp
#	g++ -std=c++11 -o runGraph main.cpp DirectedWeightedGraph.cpp LinkedList.cpp
