runGraph: UndirectedUnweightedGraph.h main.cpp NetworkAlgorithms.cpp
	g++ -std=c++11 -o runGraph main.cpp NetworkAlgorithms.cpp

#since we're using templates, it turns out that the definitions need to accompany the ip


#runGraph: LinkedList.h LinkedList.cpp DirectedWeightedGraph.h DirectedWeightedGraph.cpp main.cpp
#	g++ -std=c++11 -o runGraph main.cpp DirectedWeightedGraph.cpp LinkedList.cpp
